# Generated by Django 2.2 on 2020-10-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
    ]
